//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProjetos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PortalProjetos.PortalProjetosSoap")]
    public interface PortalProjetosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpresasH", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalProjetos.EmpresasHResponse> EmpresasHAsync(PortalProjetos.EmpresasHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpresasHom", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalProjetos.EmpresasHomResponse> EmpresasHomAsync(PortalProjetos.EmpresasHomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpresaAutenticada", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalProjetos.EmpresaAutenticadaResponse> EmpresaAutenticadaAsync(PortalProjetos.EmpresaAutenticadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtivaInativaEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<PortalProjetos.AtivaInativaEmpresaResponse> AtivaInativaEmpresaAsync(PortalProjetos.AtivaInativaEmpresaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresasHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresasH", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.EmpresasHRequestBody Body;
        
        public EmpresasHRequest()
        {
        }
        
        public EmpresasHRequest(PortalProjetos.EmpresasHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpresasHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a_DadosEmpresaH;
        
        public EmpresasHRequestBody()
        {
        }
        
        public EmpresasHRequestBody(string a_DadosEmpresaH)
        {
            this.a_DadosEmpresaH = a_DadosEmpresaH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresasHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresasHResponse", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.EmpresasHResponseBody Body;
        
        public EmpresasHResponse()
        {
        }
        
        public EmpresasHResponse(PortalProjetos.EmpresasHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpresasHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmpresasHResult;
        
        public EmpresasHResponseBody()
        {
        }
        
        public EmpresasHResponseBody(string EmpresasHResult)
        {
            this.EmpresasHResult = EmpresasHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresasHomRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresasHom", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.EmpresasHomRequestBody Body;
        
        public EmpresasHomRequest()
        {
        }
        
        public EmpresasHomRequest(PortalProjetos.EmpresasHomRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpresasHomRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a_Clientes;
        
        public EmpresasHomRequestBody()
        {
        }
        
        public EmpresasHomRequestBody(string a_Clientes)
        {
            this.a_Clientes = a_Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresasHomResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresasHomResponse", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.EmpresasHomResponseBody Body;
        
        public EmpresasHomResponse()
        {
        }
        
        public EmpresasHomResponse(PortalProjetos.EmpresasHomResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpresasHomResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmpresasHomResult;
        
        public EmpresasHomResponseBody()
        {
        }
        
        public EmpresasHomResponseBody(string EmpresasHomResult)
        {
            this.EmpresasHomResult = EmpresasHomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresaAutenticadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresaAutenticada", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.EmpresaAutenticadaRequestBody Body;
        
        public EmpresaAutenticadaRequest()
        {
        }
        
        public EmpresaAutenticadaRequest(PortalProjetos.EmpresaAutenticadaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpresaAutenticadaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a_CNPJ;
        
        public EmpresaAutenticadaRequestBody()
        {
        }
        
        public EmpresaAutenticadaRequestBody(string a_CNPJ)
        {
            this.a_CNPJ = a_CNPJ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmpresaAutenticadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmpresaAutenticadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.EmpresaAutenticadaResponseBody Body;
        
        public EmpresaAutenticadaResponse()
        {
        }
        
        public EmpresaAutenticadaResponse(PortalProjetos.EmpresaAutenticadaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpresaAutenticadaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EmpresaAutenticadaResult;
        
        public EmpresaAutenticadaResponseBody()
        {
        }
        
        public EmpresaAutenticadaResponseBody(bool EmpresaAutenticadaResult)
        {
            this.EmpresaAutenticadaResult = EmpresaAutenticadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtivaInativaEmpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtivaInativaEmpresa", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.AtivaInativaEmpresaRequestBody Body;
        
        public AtivaInativaEmpresaRequest()
        {
        }
        
        public AtivaInativaEmpresaRequest(PortalProjetos.AtivaInativaEmpresaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtivaInativaEmpresaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a_CNPJ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string a_Acao;
        
        public AtivaInativaEmpresaRequestBody()
        {
        }
        
        public AtivaInativaEmpresaRequestBody(string a_CNPJ, string a_Acao)
        {
            this.a_CNPJ = a_CNPJ;
            this.a_Acao = a_Acao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtivaInativaEmpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtivaInativaEmpresaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PortalProjetos.AtivaInativaEmpresaResponseBody Body;
        
        public AtivaInativaEmpresaResponse()
        {
        }
        
        public AtivaInativaEmpresaResponse(PortalProjetos.AtivaInativaEmpresaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtivaInativaEmpresaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AtivaInativaEmpresaResult;
        
        public AtivaInativaEmpresaResponseBody()
        {
        }
        
        public AtivaInativaEmpresaResponseBody(bool AtivaInativaEmpresaResult)
        {
            this.AtivaInativaEmpresaResult = AtivaInativaEmpresaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface PortalProjetosSoapChannel : PortalProjetos.PortalProjetosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class PortalProjetosSoapClient : System.ServiceModel.ClientBase<PortalProjetos.PortalProjetosSoap>, PortalProjetos.PortalProjetosSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PortalProjetosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PortalProjetosSoapClient.GetBindingForEndpoint(endpointConfiguration), PortalProjetosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalProjetosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PortalProjetosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalProjetosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PortalProjetosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalProjetosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalProjetos.EmpresasHResponse> PortalProjetos.PortalProjetosSoap.EmpresasHAsync(PortalProjetos.EmpresasHRequest request)
        {
            return base.Channel.EmpresasHAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalProjetos.EmpresasHResponse> EmpresasHAsync(string a_DadosEmpresaH)
        {
            PortalProjetos.EmpresasHRequest inValue = new PortalProjetos.EmpresasHRequest();
            inValue.Body = new PortalProjetos.EmpresasHRequestBody();
            inValue.Body.a_DadosEmpresaH = a_DadosEmpresaH;
            return ((PortalProjetos.PortalProjetosSoap)(this)).EmpresasHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalProjetos.EmpresasHomResponse> PortalProjetos.PortalProjetosSoap.EmpresasHomAsync(PortalProjetos.EmpresasHomRequest request)
        {
            return base.Channel.EmpresasHomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalProjetos.EmpresasHomResponse> EmpresasHomAsync(string a_Clientes)
        {
            PortalProjetos.EmpresasHomRequest inValue = new PortalProjetos.EmpresasHomRequest();
            inValue.Body = new PortalProjetos.EmpresasHomRequestBody();
            inValue.Body.a_Clientes = a_Clientes;
            return ((PortalProjetos.PortalProjetosSoap)(this)).EmpresasHomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalProjetos.EmpresaAutenticadaResponse> PortalProjetos.PortalProjetosSoap.EmpresaAutenticadaAsync(PortalProjetos.EmpresaAutenticadaRequest request)
        {
            return base.Channel.EmpresaAutenticadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalProjetos.EmpresaAutenticadaResponse> EmpresaAutenticadaAsync(string a_CNPJ)
        {
            PortalProjetos.EmpresaAutenticadaRequest inValue = new PortalProjetos.EmpresaAutenticadaRequest();
            inValue.Body = new PortalProjetos.EmpresaAutenticadaRequestBody();
            inValue.Body.a_CNPJ = a_CNPJ;
            return ((PortalProjetos.PortalProjetosSoap)(this)).EmpresaAutenticadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalProjetos.AtivaInativaEmpresaResponse> PortalProjetos.PortalProjetosSoap.AtivaInativaEmpresaAsync(PortalProjetos.AtivaInativaEmpresaRequest request)
        {
            return base.Channel.AtivaInativaEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalProjetos.AtivaInativaEmpresaResponse> AtivaInativaEmpresaAsync(string a_CNPJ, string a_Acao)
        {
            PortalProjetos.AtivaInativaEmpresaRequest inValue = new PortalProjetos.AtivaInativaEmpresaRequest();
            inValue.Body = new PortalProjetos.AtivaInativaEmpresaRequestBody();
            inValue.Body.a_CNPJ = a_CNPJ;
            inValue.Body.a_Acao = a_Acao;
            return ((PortalProjetos.PortalProjetosSoap)(this)).AtivaInativaEmpresaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalProjetosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PortalProjetosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalProjetosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.15.9/portalprojetos/portalprojetos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PortalProjetosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.15.9/portalprojetos/portalprojetos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PortalProjetosSoap,
            
            PortalProjetosSoap12,
        }
    }
}
